<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="37" total="47" passed="10">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="26183" started-at="2020-06-30T12:14:16Z" finished-at="2020-06-30T12:14:42Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="26183" started-at="2020-06-30T12:14:16Z" finished-at="2020-06-30T12:14:42Z">
      <class name="Exposure.RestAssured.setConsentTest">
        <test-method status="PASS" signature="setConsentTVTA_OPTIN_BEP1423001()[pri:1, instance:Exposure.RestAssured.setConsentTest@6f1c29b7]" name="setConsentTVTA_OPTIN_BEP1423001" duration-ms="3054" started-at="2020-06-30T12:14:37Z" finished-at="2020-06-30T12:14:40Z">
        </test-method> <!-- setConsentTVTA_OPTIN_BEP1423001 -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:Exposure.RestAssured.setConsentTest@6f1c29b7]" name="beforeTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:37Z" finished-at="2020-06-30T12:14:37Z">
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="setConsentTVReco_OPTIN_BEP1423002()[pri:2, instance:Exposure.RestAssured.setConsentTest@6f1c29b7]" name="setConsentTVReco_OPTIN_BEP1423002" duration-ms="680" started-at="2020-06-30T12:14:40Z" finished-at="2020-06-30T12:14:41Z">
        </test-method> <!-- setConsentTVReco_OPTIN_BEP1423002 -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:Exposure.RestAssured.setConsentTest@6f1c29b7]" name="beforeTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:40Z" finished-at="2020-06-30T12:14:40Z">
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:Exposure.RestAssured.setConsentTest@6f1c29b7]" name="beforeTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:41Z" finished-at="2020-06-30T12:14:41Z">
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="setConsentTVTA_OPTOUT_BEP1423003()[pri:3, instance:Exposure.RestAssured.setConsentTest@6f1c29b7]" name="setConsentTVTA_OPTOUT_BEP1423003" duration-ms="421" started-at="2020-06-30T12:14:41Z" finished-at="2020-06-30T12:14:41Z">
        </test-method> <!-- setConsentTVTA_OPTOUT_BEP1423003 -->
        <test-method status="PASS" signature="setConsentTVReco_OPTOUT_BEP1423004()[pri:4, instance:Exposure.RestAssured.setConsentTest@6f1c29b7]" name="setConsentTVReco_OPTOUT_BEP1423004" duration-ms="436" started-at="2020-06-30T12:14:41Z" finished-at="2020-06-30T12:14:42Z">
        </test-method> <!-- setConsentTVReco_OPTOUT_BEP1423004 -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:Exposure.RestAssured.setConsentTest@6f1c29b7]" name="beforeTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:41Z" finished-at="2020-06-30T12:14:41Z">
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:Exposure.RestAssured.setConsentTest@6f1c29b7]" name="beforeTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:42Z" finished-at="2020-06-30T12:14:42Z">
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="setConsentwithInvalidConsentType_BEP1423005()[pri:5, instance:Exposure.RestAssured.setConsentTest@6f1c29b7]" name="setConsentwithInvalidConsentType_BEP1423005" duration-ms="319" started-at="2020-06-30T12:14:42Z" finished-at="2020-06-30T12:14:42Z">
        </test-method> <!-- setConsentwithInvalidConsentType_BEP1423005 -->
        <test-method status="PASS" signature="setConsentwithInvalidConsentValue_BEP1423006()[pri:5, instance:Exposure.RestAssured.setConsentTest@6f1c29b7]" name="setConsentwithInvalidConsentValue_BEP1423006" duration-ms="227" started-at="2020-06-30T12:14:42Z" finished-at="2020-06-30T12:14:42Z">
        </test-method> <!-- setConsentwithInvalidConsentValue_BEP1423006 -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:Exposure.RestAssured.setConsentTest@6f1c29b7]" name="beforeTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:42Z" finished-at="2020-06-30T12:14:42Z">
        </test-method> <!-- beforeTest -->
      </class> <!-- Exposure.RestAssured.setConsentTest -->
      <class name="Exposure.RestAssured.ReminderTests">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="beforeSuite" is-config="true" duration-ms="857" started-at="2020-06-30T12:14:15Z" finished-at="2020-06-30T12:14:16Z">
        </test-method> <!-- beforeSuite -->
        <test-method status="FAIL" signature="addReminderWithInterfaceVersion520_BEP14470001()[pri:1, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="addReminderWithInterfaceVersion520_BEP14470001" duration-ms="2803" started-at="2020-06-30T12:14:16Z" finished-at="2020-06-30T12:14:19Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<null> but was:<>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<null> but was:<>
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:160)
	at Exposure.RestAssured.ReminderTests.addReminderWithInterfaceVersion520_BEP14470001(ReminderTests.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1188)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1113)
	at org.testng.TestNG.run(TestNG.java:1025)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
        </test-method> <!-- addReminderWithInterfaceVersion520_BEP14470001 -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="beforeTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:16Z" finished-at="2020-06-30T12:14:16Z">
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="beforeTest" is-config="true" duration-ms="1" started-at="2020-06-30T12:14:19Z" finished-at="2020-06-30T12:14:19Z">
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="afterTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:19Z" finished-at="2020-06-30T12:14:19Z">
        </test-method> <!-- afterTest -->
        <test-method status="FAIL" signature="addReminderWithInterfaceVersion420_BEP14470004()[pri:2, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="addReminderWithInterfaceVersion420_BEP14470004" duration-ms="1086" started-at="2020-06-30T12:14:19Z" finished-at="2020-06-30T12:14:20Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<null> but was:<>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<null> but was:<>
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:160)
	at Exposure.RestAssured.ReminderTests.addReminderWithInterfaceVersion420_BEP14470004(ReminderTests.java:107)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1188)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1113)
	at org.testng.TestNG.run(TestNG.java:1025)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
        </test-method> <!-- addReminderWithInterfaceVersion420_BEP14470004 -->
        <test-method status="FAIL" signature="addReminderWithoutInterfaceVersion_BEP14470002()[pri:3, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="addReminderWithoutInterfaceVersion_BEP14470002" duration-ms="710" started-at="2020-06-30T12:14:20Z" finished-at="2020-06-30T12:14:21Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<Mandatory Parameter Interface Version missing> but was:<InterfaceVersion missing.>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<Mandatory Parameter Interface Version missing> but was:<InterfaceVersion missing.>
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:160)
	at Exposure.RestAssured.ReminderTests.addReminderWithoutInterfaceVersion_BEP14470002(ReminderTests.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1188)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1113)
	at org.testng.TestNG.run(TestNG.java:1025)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
        </test-method> <!-- addReminderWithoutInterfaceVersion_BEP14470002 -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="beforeTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:20Z" finished-at="2020-06-30T12:14:20Z">
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="afterTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:20Z" finished-at="2020-06-30T12:14:20Z">
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="afterTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:21Z" finished-at="2020-06-30T12:14:21Z">
        </test-method> <!-- afterTest -->
        <test-method status="FAIL" signature="addReminderWithInterfaceVersionLessThan420_BEP14470003()[pri:4, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="addReminderWithInterfaceVersionLessThan420_BEP14470003" duration-ms="737" started-at="2020-06-30T12:14:21Z" finished-at="2020-06-30T12:14:22Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<Invalid Interface version> but was:<Mandatory parameter is missing. Supported types are MAC, DeviceID, AccountNumber as request parameter or GID as request header.>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<Invalid Interface version> but was:<Mandatory parameter is missing. Supported types are MAC, DeviceID, AccountNumber as request parameter or GID as request header.>
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:160)
	at Exposure.RestAssured.ReminderTests.addReminderWithInterfaceVersionLessThan420_BEP14470003(ReminderTests.java:128)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1188)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1113)
	at org.testng.TestNG.run(TestNG.java:1025)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
        </test-method> <!-- addReminderWithInterfaceVersionLessThan420_BEP14470003 -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="beforeTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:21Z" finished-at="2020-06-30T12:14:21Z">
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="addReminderWithoutMac_BEP14470005()[pri:5, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="addReminderWithoutMac_BEP14470005" duration-ms="724" started-at="2020-06-30T12:14:22Z" finished-at="2020-06-30T12:14:22Z">
        </test-method> <!-- addReminderWithoutMac_BEP14470005 -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="afterTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:22Z" finished-at="2020-06-30T12:14:22Z">
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="beforeTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:22Z" finished-at="2020-06-30T12:14:22Z">
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="addReminderWithInvalidMac_BEP14470006()[pri:6, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="addReminderWithInvalidMac_BEP14470006" duration-ms="1020" started-at="2020-06-30T12:14:22Z" finished-at="2020-06-30T12:14:23Z">
        </test-method> <!-- addReminderWithInvalidMac_BEP14470006 -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="beforeTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:22Z" finished-at="2020-06-30T12:14:22Z">
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="afterTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:22Z" finished-at="2020-06-30T12:14:22Z">
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="afterTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:23Z" finished-at="2020-06-30T12:14:23Z">
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="beforeTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:23Z" finished-at="2020-06-30T12:14:23Z">
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="addReminderWithBlankValueForReminderType_BEP14470007()[pri:7, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="addReminderWithBlankValueForReminderType_BEP14470007" duration-ms="725" started-at="2020-06-30T12:14:23Z" finished-at="2020-06-30T12:14:24Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<Reminder Type tag is either missing or empty> but was:<Mandatory parameter is missing. Supported types are MAC, DeviceID, AccountNumber as request parameter or GID as request header.>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<Reminder Type tag is either missing or empty> but was:<Mandatory parameter is missing. Supported types are MAC, DeviceID, AccountNumber as request parameter or GID as request header.>
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:160)
	at Exposure.RestAssured.ReminderTests.addReminderWithBlankValueForReminderType_BEP14470007(ReminderTests.java:162)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1188)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1113)
	at org.testng.TestNG.run(TestNG.java:1025)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
        </test-method> <!-- addReminderWithBlankValueForReminderType_BEP14470007 -->
        <test-method status="FAIL" signature="addReminderWithoutReminderTag_BEP14470008()[pri:8, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="addReminderWithoutReminderTag_BEP14470008" duration-ms="726" started-at="2020-06-30T12:14:24Z" finished-at="2020-06-30T12:14:25Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<Reminder Type tag is either missing or empty> but was:<Mandatory parameter is missing. Supported types are MAC, DeviceID, AccountNumber as request parameter or GID as request header.>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<Reminder Type tag is either missing or empty> but was:<Mandatory parameter is missing. Supported types are MAC, DeviceID, AccountNumber as request parameter or GID as request header.>
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:160)
	at Exposure.RestAssured.ReminderTests.addReminderWithoutReminderTag_BEP14470008(ReminderTests.java:174)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1188)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1113)
	at org.testng.TestNG.run(TestNG.java:1025)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
        </test-method> <!-- addReminderWithoutReminderTag_BEP14470008 -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="beforeTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:24Z" finished-at="2020-06-30T12:14:24Z">
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="afterTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:24Z" finished-at="2020-06-30T12:14:24Z">
        </test-method> <!-- afterTest -->
        <test-method status="FAIL" signature="addReminderWithBlankValueforMinsBeforeStart_BEP14470009()[pri:9, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="addReminderWithBlankValueforMinsBeforeStart_BEP14470009" duration-ms="720" started-at="2020-06-30T12:14:25Z" finished-at="2020-06-30T12:14:25Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<Mins Before Start tag is either missing/empty/incorrect> but was:<Mandatory parameter is missing. Supported types are MAC, DeviceID, AccountNumber as request parameter or GID as request header.>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<Mins Before Start tag is either missing/empty/incorrect> but was:<Mandatory parameter is missing. Supported types are MAC, DeviceID, AccountNumber as request parameter or GID as request header.>
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:160)
	at Exposure.RestAssured.ReminderTests.addReminderWithBlankValueforMinsBeforeStart_BEP14470009(ReminderTests.java:185)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1188)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1113)
	at org.testng.TestNG.run(TestNG.java:1025)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
        </test-method> <!-- addReminderWithBlankValueforMinsBeforeStart_BEP14470009 -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="beforeTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:25Z" finished-at="2020-06-30T12:14:25Z">
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="afterTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:25Z" finished-at="2020-06-30T12:14:25Z">
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="afterTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:25Z" finished-at="2020-06-30T12:14:25Z">
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="beforeTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:25Z" finished-at="2020-06-30T12:14:25Z">
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="addReminderWithoutMinsBeforeStartTag_BEP144700010()[pri:10, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="addReminderWithoutMinsBeforeStartTag_BEP144700010" duration-ms="725" started-at="2020-06-30T12:14:25Z" finished-at="2020-06-30T12:14:26Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<Mins Before Start tag is either missing/empty/incorrect> but was:<Mandatory parameter is missing. Supported types are MAC, DeviceID, AccountNumber as request parameter or GID as request header.>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<Mins Before Start tag is either missing/empty/incorrect> but was:<Mandatory parameter is missing. Supported types are MAC, DeviceID, AccountNumber as request parameter or GID as request header.>
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:160)
	at Exposure.RestAssured.ReminderTests.addReminderWithoutMinsBeforeStartTag_BEP144700010(ReminderTests.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1188)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1113)
	at org.testng.TestNG.run(TestNG.java:1025)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
        </test-method> <!-- addReminderWithoutMinsBeforeStartTag_BEP144700010 -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="afterTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:26Z" finished-at="2020-06-30T12:14:26Z">
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="beforeTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:26Z" finished-at="2020-06-30T12:14:26Z">
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="addReminderWithBlankValueForSchTrailID_BEP144700011()[pri:11, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="addReminderWithBlankValueForSchTrailID_BEP144700011" duration-ms="942" started-at="2020-06-30T12:14:26Z" finished-at="2020-06-30T12:14:27Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<Schedule Trail Id tag is either missing/empty/incorrect> but was:<Mandatory parameter is missing. Supported types are MAC, DeviceID, AccountNumber as request parameter or GID as request header.>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<Schedule Trail Id tag is either missing/empty/incorrect> but was:<Mandatory parameter is missing. Supported types are MAC, DeviceID, AccountNumber as request parameter or GID as request header.>
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:160)
	at Exposure.RestAssured.ReminderTests.addReminderWithBlankValueForSchTrailID_BEP144700011(ReminderTests.java:207)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1188)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1113)
	at org.testng.TestNG.run(TestNG.java:1025)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
        </test-method> <!-- addReminderWithBlankValueForSchTrailID_BEP144700011 -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="beforeTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:27Z" finished-at="2020-06-30T12:14:27Z">
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="addReminderWithoutSchTrailIDTag_BEP144700012()[pri:12, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="addReminderWithoutSchTrailIDTag_BEP144700012" duration-ms="918" started-at="2020-06-30T12:14:27Z" finished-at="2020-06-30T12:14:28Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<Schedule Trail Id tag is either missing/empty/incorrect> but was:<Mandatory parameter is missing. Supported types are MAC, DeviceID, AccountNumber as request parameter or GID as request header.>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<Schedule Trail Id tag is either missing/empty/incorrect> but was:<Mandatory parameter is missing. Supported types are MAC, DeviceID, AccountNumber as request parameter or GID as request header.>
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:160)
	at Exposure.RestAssured.ReminderTests.addReminderWithoutSchTrailIDTag_BEP144700012(ReminderTests.java:218)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1188)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1113)
	at org.testng.TestNG.run(TestNG.java:1025)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
        </test-method> <!-- addReminderWithoutSchTrailIDTag_BEP144700012 -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="afterTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:27Z" finished-at="2020-06-30T12:14:27Z">
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="afterTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:28Z" finished-at="2020-06-30T12:14:28Z">
        </test-method> <!-- afterTest -->
        <test-method status="FAIL" signature="addReminderWithBlankValueForChannelExtID_BEP144700013()[pri:13, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="addReminderWithBlankValueForChannelExtID_BEP144700013" duration-ms="947" started-at="2020-06-30T12:14:28Z" finished-at="2020-06-30T12:14:29Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<Channel External Id tag is either missing/empty> but was:<Mandatory parameter is missing. Supported types are MAC, DeviceID, AccountNumber as request parameter or GID as request header.>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<Channel External Id tag is either missing/empty> but was:<Mandatory parameter is missing. Supported types are MAC, DeviceID, AccountNumber as request parameter or GID as request header.>
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:160)
	at Exposure.RestAssured.ReminderTests.addReminderWithBlankValueForChannelExtID_BEP144700013(ReminderTests.java:229)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1188)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1113)
	at org.testng.TestNG.run(TestNG.java:1025)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
        </test-method> <!-- addReminderWithBlankValueForChannelExtID_BEP144700013 -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="beforeTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:28Z" finished-at="2020-06-30T12:14:28Z">
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="addReminderWithoutChannelExtID_BEP144700014()[pri:14, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="addReminderWithoutChannelExtID_BEP144700014" duration-ms="912" started-at="2020-06-30T12:14:29Z" finished-at="2020-06-30T12:14:30Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<Channel External Id tag is either missing/empty> but was:<Mandatory parameter is missing. Supported types are MAC, DeviceID, AccountNumber as request parameter or GID as request header.>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<Channel External Id tag is either missing/empty> but was:<Mandatory parameter is missing. Supported types are MAC, DeviceID, AccountNumber as request parameter or GID as request header.>
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:160)
	at Exposure.RestAssured.ReminderTests.addReminderWithoutChannelExtID_BEP144700014(ReminderTests.java:241)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1188)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1113)
	at org.testng.TestNG.run(TestNG.java:1025)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
        </test-method> <!-- addReminderWithoutChannelExtID_BEP144700014 -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="afterTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:29Z" finished-at="2020-06-30T12:14:29Z">
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="beforeTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:29Z" finished-at="2020-06-30T12:14:29Z">
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="afterTest" is-config="true" duration-ms="1" started-at="2020-06-30T12:14:30Z" finished-at="2020-06-30T12:14:30Z">
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="beforeTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:30Z" finished-at="2020-06-30T12:14:30Z">
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="addReminderWhenIcorrectSchTrailID_BEP144700016()[pri:15, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="addReminderWhenIcorrectSchTrailID_BEP144700016" duration-ms="1167" started-at="2020-06-30T12:14:30Z" finished-at="2020-06-30T12:14:31Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<Schedule Trail Id does not exists> but was:<Mandatory parameter is missing. Supported types are MAC, DeviceID, AccountNumber as request parameter or GID as request header.>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<Schedule Trail Id does not exists> but was:<Mandatory parameter is missing. Supported types are MAC, DeviceID, AccountNumber as request parameter or GID as request header.>
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:160)
	at Exposure.RestAssured.ReminderTests.addReminderWhenIcorrectSchTrailID_BEP144700016(ReminderTests.java:252)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1188)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1113)
	at org.testng.TestNG.run(TestNG.java:1025)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
        </test-method> <!-- addReminderWhenIcorrectSchTrailID_BEP144700016 -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="beforeTest" is-config="true" duration-ms="1" started-at="2020-06-30T12:14:31Z" finished-at="2020-06-30T12:14:31Z">
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="afterTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:31Z" finished-at="2020-06-30T12:14:31Z">
        </test-method> <!-- afterTest -->
        <test-method status="FAIL" signature="addReminderWhenIcorrectChannelExtID_BEP144700017()[pri:16, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="addReminderWhenIcorrectChannelExtID_BEP144700017" duration-ms="1178" started-at="2020-06-30T12:14:31Z" finished-at="2020-06-30T12:14:32Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<Channel External Id does not exists> but was:<Mandatory parameter is missing. Supported types are MAC, DeviceID, AccountNumber as request parameter or GID as request header.>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<Channel External Id does not exists> but was:<Mandatory parameter is missing. Supported types are MAC, DeviceID, AccountNumber as request parameter or GID as request header.>
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:160)
	at Exposure.RestAssured.ReminderTests.addReminderWhenIcorrectChannelExtID_BEP144700017(ReminderTests.java:263)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1188)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1113)
	at org.testng.TestNG.run(TestNG.java:1025)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
        </test-method> <!-- addReminderWhenIcorrectChannelExtID_BEP144700017 -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="afterTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:32Z" finished-at="2020-06-30T12:14:32Z">
        </test-method> <!-- afterTest -->
        <test-method status="FAIL" signature="addReminderWhenMinsBeforeStartIsnotCorrect_BEP144700018()[pri:17, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="addReminderWhenMinsBeforeStartIsnotCorrect_BEP144700018" duration-ms="690" started-at="2020-06-30T12:14:32Z" finished-at="2020-06-30T12:14:33Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<Mins Before Start value should be between 0 and 99> but was:<Mandatory parameter is missing. Supported types are MAC, DeviceID, AccountNumber as request parameter or GID as request header.>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<Mins Before Start value should be between 0 and 99> but was:<Mandatory parameter is missing. Supported types are MAC, DeviceID, AccountNumber as request parameter or GID as request header.>
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:160)
	at Exposure.RestAssured.ReminderTests.addReminderWhenMinsBeforeStartIsnotCorrect_BEP144700018(ReminderTests.java:275)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1188)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1113)
	at org.testng.TestNG.run(TestNG.java:1025)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
        </test-method> <!-- addReminderWhenMinsBeforeStartIsnotCorrect_BEP144700018 -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="beforeTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:32Z" finished-at="2020-06-30T12:14:32Z">
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="getReminderBTACall_BEP14477001()[pri:18, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="getReminderBTACall_BEP14477001" duration-ms="250" started-at="2020-06-30T12:14:33Z" finished-at="2020-06-30T12:14:33Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<null> but was:<>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<null> but was:<>
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:160)
	at Exposure.RestAssured.ReminderTests.getReminderBTACall_BEP14477001(ReminderTests.java:290)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1188)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1113)
	at org.testng.TestNG.run(TestNG.java:1025)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
        </test-method> <!-- getReminderBTACall_BEP14477001 -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="beforeTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:33Z" finished-at="2020-06-30T12:14:33Z">
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="afterTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:33Z" finished-at="2020-06-30T12:14:33Z">
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="beforeTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:33Z" finished-at="2020-06-30T12:14:33Z">
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="afterTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:33Z" finished-at="2020-06-30T12:14:33Z">
        </test-method> <!-- afterTest -->
        <test-method status="FAIL" signature="getReminderBTACall_BEP14477002()[pri:19, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="getReminderBTACall_BEP14477002" duration-ms="108" started-at="2020-06-30T12:14:33Z" finished-at="2020-06-30T12:14:33Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<Mandatory Parameter Interface Version missing> but was:<InterfaceVersion missing.>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<Mandatory Parameter Interface Version missing> but was:<InterfaceVersion missing.>
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:160)
	at Exposure.RestAssured.ReminderTests.getReminderBTACall_BEP14477002(ReminderTests.java:304)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1188)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1113)
	at org.testng.TestNG.run(TestNG.java:1025)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
        </test-method> <!-- getReminderBTACall_BEP14477002 -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="beforeTest" is-config="true" duration-ms="1" started-at="2020-06-30T12:14:33Z" finished-at="2020-06-30T12:14:33Z">
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="afterTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:33Z" finished-at="2020-06-30T12:14:33Z">
        </test-method> <!-- afterTest -->
        <test-method status="FAIL" signature="getReminderBTACall_BEP14477003()[pri:20, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="getReminderBTACall_BEP14477003" duration-ms="147" started-at="2020-06-30T12:14:33Z" finished-at="2020-06-30T12:14:33Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<Invalid Interface version> but was:<Mandatory parameter is missing. Supported types are MAC, DeviceID, AccountNumber as request parameter or GID as request header.>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<Invalid Interface version> but was:<Mandatory parameter is missing. Supported types are MAC, DeviceID, AccountNumber as request parameter or GID as request header.>
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:160)
	at Exposure.RestAssured.ReminderTests.getReminderBTACall_BEP14477003(ReminderTests.java:319)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1188)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1113)
	at org.testng.TestNG.run(TestNG.java:1025)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
        </test-method> <!-- getReminderBTACall_BEP14477003 -->
        <test-method status="PASS" signature="getReminderBTACall_BEP14477004()[pri:21, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="getReminderBTACall_BEP14477004" duration-ms="181" started-at="2020-06-30T12:14:33Z" finished-at="2020-06-30T12:14:34Z">
        </test-method> <!-- getReminderBTACall_BEP14477004 -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="afterTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:33Z" finished-at="2020-06-30T12:14:33Z">
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="beforeTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:33Z" finished-at="2020-06-30T12:14:33Z">
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="getReminderBTACall_BEP14477005()[pri:22, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="getReminderBTACall_BEP14477005" duration-ms="44" started-at="2020-06-30T12:14:34Z" finished-at="2020-06-30T12:14:34Z">
        </test-method> <!-- getReminderBTACall_BEP14477005 -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="afterTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:34Z" finished-at="2020-06-30T12:14:34Z">
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="beforeTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:34Z" finished-at="2020-06-30T12:14:34Z">
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="updateReminder_BEP14471001()[pri:23, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="updateReminder_BEP14471001" duration-ms="141" started-at="2020-06-30T12:14:34Z" finished-at="2020-06-30T12:14:34Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at base.Testbase.executeSelectQuery(Testbase.java:209)
	at testData.TestDataCreation.createPOSTBodyForReminder(TestDataCreation.java:68)
	at Exposure.RestAssured.ReminderTests.updateReminder_BEP14471001(ReminderTests.java:356)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1188)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1113)
	at org.testng.TestNG.run(TestNG.java:1025)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
        </test-method> <!-- updateReminder_BEP14471001 -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="afterTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:34Z" finished-at="2020-06-30T12:14:34Z">
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="beforeTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:34Z" finished-at="2020-06-30T12:14:34Z">
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="beforeTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:34Z" finished-at="2020-06-30T12:14:34Z">
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="afterTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:34Z" finished-at="2020-06-30T12:14:34Z">
        </test-method> <!-- afterTest -->
        <test-method status="FAIL" signature="updateReminderWithoutInterfaceVersion_BEP14471002()[pri:24, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="updateReminderWithoutInterfaceVersion_BEP14471002" duration-ms="354" started-at="2020-06-30T12:14:34Z" finished-at="2020-06-30T12:14:34Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at base.Testbase.executeSelectQuery(Testbase.java:209)
	at testData.TestDataCreation.createPOSTBodyForReminder(TestDataCreation.java:68)
	at Exposure.RestAssured.ReminderTests.updateReminderWithoutInterfaceVersion_BEP14471002(ReminderTests.java:374)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1188)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1113)
	at org.testng.TestNG.run(TestNG.java:1025)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
        </test-method> <!-- updateReminderWithoutInterfaceVersion_BEP14471002 -->
        <test-method status="FAIL" signature="updateReminderWhenInterfaceVersionLessThen420_BEP14471003()[pri:25, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="updateReminderWhenInterfaceVersionLessThen420_BEP14471003" duration-ms="362" started-at="2020-06-30T12:14:34Z" finished-at="2020-06-30T12:14:35Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at base.Testbase.executeSelectQuery(Testbase.java:209)
	at testData.TestDataCreation.createPOSTBodyForReminder(TestDataCreation.java:68)
	at Exposure.RestAssured.ReminderTests.updateReminderWhenInterfaceVersionLessThen420_BEP14471003(ReminderTests.java:387)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1188)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1113)
	at org.testng.TestNG.run(TestNG.java:1025)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
        </test-method> <!-- updateReminderWhenInterfaceVersionLessThen420_BEP14471003 -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="beforeTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:34Z" finished-at="2020-06-30T12:14:34Z">
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="afterTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:34Z" finished-at="2020-06-30T12:14:34Z">
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="beforeTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:35Z" finished-at="2020-06-30T12:14:35Z">
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="afterTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:35Z" finished-at="2020-06-30T12:14:35Z">
        </test-method> <!-- afterTest -->
        <test-method status="FAIL" signature="updateReminderWithoutMac_BEP14471004()[pri:26, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="updateReminderWithoutMac_BEP14471004" duration-ms="354" started-at="2020-06-30T12:14:35Z" finished-at="2020-06-30T12:14:35Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at base.Testbase.executeSelectQuery(Testbase.java:209)
	at testData.TestDataCreation.createPOSTBodyForReminder(TestDataCreation.java:68)
	at Exposure.RestAssured.ReminderTests.updateReminderWithoutMac_BEP14471004(ReminderTests.java:400)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1188)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1113)
	at org.testng.TestNG.run(TestNG.java:1025)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
        </test-method> <!-- updateReminderWithoutMac_BEP14471004 -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="afterTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:35Z" finished-at="2020-06-30T12:14:35Z">
        </test-method> <!-- afterTest -->
        <test-method status="FAIL" signature="updateReminderWithInvalidMac_BEP14471005()[pri:27, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="updateReminderWithInvalidMac_BEP14471005" duration-ms="356" started-at="2020-06-30T12:14:35Z" finished-at="2020-06-30T12:14:35Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at base.Testbase.executeSelectQuery(Testbase.java:209)
	at testData.TestDataCreation.createPOSTBodyForReminder(TestDataCreation.java:68)
	at Exposure.RestAssured.ReminderTests.updateReminderWithInvalidMac_BEP14471005(ReminderTests.java:412)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1188)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1113)
	at org.testng.TestNG.run(TestNG.java:1025)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
        </test-method> <!-- updateReminderWithInvalidMac_BEP14471005 -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="beforeTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:35Z" finished-at="2020-06-30T12:14:35Z">
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="afterTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:35Z" finished-at="2020-06-30T12:14:35Z">
        </test-method> <!-- afterTest -->
        <test-method status="FAIL" signature="updateReminderWithBlankValueForID_BEP14471006()[pri:28, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="updateReminderWithBlankValueForID_BEP14471006" duration-ms="131" started-at="2020-06-30T12:14:35Z" finished-at="2020-06-30T12:14:35Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at base.Testbase.executeSelectQuery(Testbase.java:209)
	at testData.TestDataCreation.createPOSTBodyForReminder(TestDataCreation.java:68)
	at Exposure.RestAssured.ReminderTests.updateReminderWithBlankValueForID_BEP14471006(ReminderTests.java:423)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1188)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1113)
	at org.testng.TestNG.run(TestNG.java:1025)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
        </test-method> <!-- updateReminderWithBlankValueForID_BEP14471006 -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="beforeTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:35Z" finished-at="2020-06-30T12:14:35Z">
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="afterTest" is-config="true" duration-ms="1" started-at="2020-06-30T12:14:35Z" finished-at="2020-06-30T12:14:35Z">
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="beforeTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:35Z" finished-at="2020-06-30T12:14:35Z">
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="updateReminderWithoutIDTag_BEP14471007()[pri:29, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="updateReminderWithoutIDTag_BEP14471007" duration-ms="139" started-at="2020-06-30T12:14:35Z" finished-at="2020-06-30T12:14:36Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at base.Testbase.executeSelectQuery(Testbase.java:209)
	at testData.TestDataCreation.createPOSTBodyForReminder(TestDataCreation.java:68)
	at Exposure.RestAssured.ReminderTests.updateReminderWithoutIDTag_BEP14471007(ReminderTests.java:435)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1188)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1113)
	at org.testng.TestNG.run(TestNG.java:1025)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
        </test-method> <!-- updateReminderWithoutIDTag_BEP14471007 -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="afterTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:36Z" finished-at="2020-06-30T12:14:36Z">
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="beforeTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:36Z" finished-at="2020-06-30T12:14:36Z">
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="updateReminderWithBlankValueForReminderType_BEP14471008()[pri:30, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="updateReminderWithBlankValueForReminderType_BEP14471008" duration-ms="137" started-at="2020-06-30T12:14:36Z" finished-at="2020-06-30T12:14:36Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at base.Testbase.executeSelectQuery(Testbase.java:209)
	at testData.TestDataCreation.createPOSTBodyForReminder(TestDataCreation.java:68)
	at Exposure.RestAssured.ReminderTests.updateReminderWithBlankValueForReminderType_BEP14471008(ReminderTests.java:446)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1188)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1113)
	at org.testng.TestNG.run(TestNG.java:1025)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
        </test-method> <!-- updateReminderWithBlankValueForReminderType_BEP14471008 -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="beforeTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:36Z" finished-at="2020-06-30T12:14:36Z">
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="afterTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:36Z" finished-at="2020-06-30T12:14:36Z">
        </test-method> <!-- afterTest -->
        <test-method status="FAIL" signature="updateReminderWithoutReminderTag_BEP14471009()[pri:31, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="updateReminderWithoutReminderTag_BEP14471009" duration-ms="134" started-at="2020-06-30T12:14:36Z" finished-at="2020-06-30T12:14:36Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at base.Testbase.executeSelectQuery(Testbase.java:209)
	at testData.TestDataCreation.createPOSTBodyForReminder(TestDataCreation.java:68)
	at Exposure.RestAssured.ReminderTests.updateReminderWithoutReminderTag_BEP14471009(ReminderTests.java:458)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1188)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1113)
	at org.testng.TestNG.run(TestNG.java:1025)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
        </test-method> <!-- updateReminderWithoutReminderTag_BEP14471009 -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="beforeTest" is-config="true" duration-ms="1" started-at="2020-06-30T12:14:36Z" finished-at="2020-06-30T12:14:36Z">
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="afterTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:36Z" finished-at="2020-06-30T12:14:36Z">
        </test-method> <!-- afterTest -->
        <test-method status="FAIL" signature="updateReminderWithBlankValueforMinsBeforeStart_BEP144710010()[pri:32, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="updateReminderWithBlankValueforMinsBeforeStart_BEP144710010" duration-ms="143" started-at="2020-06-30T12:14:36Z" finished-at="2020-06-30T12:14:36Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at base.Testbase.executeSelectQuery(Testbase.java:209)
	at testData.TestDataCreation.createPOSTBodyForReminder(TestDataCreation.java:68)
	at Exposure.RestAssured.ReminderTests.updateReminderWithBlankValueforMinsBeforeStart_BEP144710010(ReminderTests.java:470)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1188)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1113)
	at org.testng.TestNG.run(TestNG.java:1025)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
        </test-method> <!-- updateReminderWithBlankValueforMinsBeforeStart_BEP144710010 -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="beforeTest" is-config="true" duration-ms="1" started-at="2020-06-30T12:14:36Z" finished-at="2020-06-30T12:14:36Z">
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="afterTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:36Z" finished-at="2020-06-30T12:14:36Z">
        </test-method> <!-- afterTest -->
        <test-method status="FAIL" signature="updateReminderWithoutMinsBeforeStartTag_BEP144710011()[pri:33, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="updateReminderWithoutMinsBeforeStartTag_BEP144710011" duration-ms="139" started-at="2020-06-30T12:14:36Z" finished-at="2020-06-30T12:14:36Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at base.Testbase.executeSelectQuery(Testbase.java:209)
	at testData.TestDataCreation.createPOSTBodyForReminder(TestDataCreation.java:68)
	at Exposure.RestAssured.ReminderTests.updateReminderWithoutMinsBeforeStartTag_BEP144710011(ReminderTests.java:482)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1188)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1113)
	at org.testng.TestNG.run(TestNG.java:1025)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
        </test-method> <!-- updateReminderWithoutMinsBeforeStartTag_BEP144710011 -->
        <test-method status="FAIL" signature="updateReminderWithBlankValueForSchTrailID_BEP144710012()[pri:34, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="updateReminderWithBlankValueForSchTrailID_BEP144710012" duration-ms="149" started-at="2020-06-30T12:14:36Z" finished-at="2020-06-30T12:14:36Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at base.Testbase.executeSelectQuery(Testbase.java:209)
	at testData.TestDataCreation.createPOSTBodyForReminder(TestDataCreation.java:68)
	at Exposure.RestAssured.ReminderTests.updateReminderWithBlankValueForSchTrailID_BEP144710012(ReminderTests.java:494)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1188)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1113)
	at org.testng.TestNG.run(TestNG.java:1025)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
        </test-method> <!-- updateReminderWithBlankValueForSchTrailID_BEP144710012 -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="afterTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:36Z" finished-at="2020-06-30T12:14:36Z">
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="beforeTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:36Z" finished-at="2020-06-30T12:14:36Z">
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="afterTest" is-config="true" duration-ms="1" started-at="2020-06-30T12:14:36Z" finished-at="2020-06-30T12:14:36Z">
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="beforeTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:36Z" finished-at="2020-06-30T12:14:36Z">
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="updateReminderWithoutSchTrailIDTag_BEP144710013()[pri:35, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="updateReminderWithoutSchTrailIDTag_BEP144710013" duration-ms="143" started-at="2020-06-30T12:14:36Z" finished-at="2020-06-30T12:14:36Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at base.Testbase.executeSelectQuery(Testbase.java:209)
	at testData.TestDataCreation.createPOSTBodyForReminder(TestDataCreation.java:68)
	at Exposure.RestAssured.ReminderTests.updateReminderWithoutSchTrailIDTag_BEP144710013(ReminderTests.java:506)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1188)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1113)
	at org.testng.TestNG.run(TestNG.java:1025)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
        </test-method> <!-- updateReminderWithoutSchTrailIDTag_BEP144710013 -->
        <test-method status="FAIL" signature="updateReminderWithBlankValueForChannelExtID_BEP144710014()[pri:36, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="updateReminderWithBlankValueForChannelExtID_BEP144710014" duration-ms="134" started-at="2020-06-30T12:14:36Z" finished-at="2020-06-30T12:14:37Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at base.Testbase.executeSelectQuery(Testbase.java:209)
	at testData.TestDataCreation.createPOSTBodyForReminder(TestDataCreation.java:68)
	at Exposure.RestAssured.ReminderTests.updateReminderWithBlankValueForChannelExtID_BEP144710014(ReminderTests.java:518)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1188)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1113)
	at org.testng.TestNG.run(TestNG.java:1025)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
        </test-method> <!-- updateReminderWithBlankValueForChannelExtID_BEP144710014 -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="beforeTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:36Z" finished-at="2020-06-30T12:14:36Z">
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="afterTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:36Z" finished-at="2020-06-30T12:14:36Z">
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="afterTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:37Z" finished-at="2020-06-30T12:14:37Z">
        </test-method> <!-- afterTest -->
        <test-method status="FAIL" signature="updateReminderWithoutChannelExtID_BEP144710015()[pri:37, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="updateReminderWithoutChannelExtID_BEP144710015" duration-ms="143" started-at="2020-06-30T12:14:37Z" finished-at="2020-06-30T12:14:37Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at base.Testbase.executeSelectQuery(Testbase.java:209)
	at testData.TestDataCreation.createPOSTBodyForReminder(TestDataCreation.java:68)
	at Exposure.RestAssured.ReminderTests.updateReminderWithoutChannelExtID_BEP144710015(ReminderTests.java:530)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1188)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1113)
	at org.testng.TestNG.run(TestNG.java:1025)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
        </test-method> <!-- updateReminderWithoutChannelExtID_BEP144710015 -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="beforeTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:37Z" finished-at="2020-06-30T12:14:37Z">
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="beforeTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:37Z" finished-at="2020-06-30T12:14:37Z">
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="afterTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:37Z" finished-at="2020-06-30T12:14:37Z">
        </test-method> <!-- afterTest -->
        <test-method status="FAIL" signature="updateReminderWhenIcorrectSchTrailID_BEP144710018()[pri:38, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="updateReminderWhenIcorrectSchTrailID_BEP144710018" duration-ms="137" started-at="2020-06-30T12:14:37Z" finished-at="2020-06-30T12:14:37Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at base.Testbase.executeSelectQuery(Testbase.java:209)
	at testData.TestDataCreation.createPOSTBodyForReminder(TestDataCreation.java:68)
	at Exposure.RestAssured.ReminderTests.updateReminderWhenIcorrectSchTrailID_BEP144710018(ReminderTests.java:543)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1188)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1113)
	at org.testng.TestNG.run(TestNG.java:1025)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
        </test-method> <!-- updateReminderWhenIcorrectSchTrailID_BEP144710018 -->
        <test-method status="FAIL" signature="updateReminderWhenIcorrectChannelExtID_BEP144710019()[pri:39, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="updateReminderWhenIcorrectChannelExtID_BEP144710019" duration-ms="143" started-at="2020-06-30T12:14:37Z" finished-at="2020-06-30T12:14:37Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at base.Testbase.executeSelectQuery(Testbase.java:209)
	at testData.TestDataCreation.createPOSTBodyForReminder(TestDataCreation.java:68)
	at Exposure.RestAssured.ReminderTests.updateReminderWhenIcorrectChannelExtID_BEP144710019(ReminderTests.java:555)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1188)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1113)
	at org.testng.TestNG.run(TestNG.java:1025)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
        </test-method> <!-- updateReminderWhenIcorrectChannelExtID_BEP144710019 -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="beforeTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:37Z" finished-at="2020-06-30T12:14:37Z">
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="afterTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:37Z" finished-at="2020-06-30T12:14:37Z">
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="afterTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:37Z" finished-at="2020-06-30T12:14:37Z">
        </test-method> <!-- afterTest -->
        <test-method status="FAIL" signature="updateReminderWhenMinsBeforeStartIsnotCorrect_BEP144710020()[pri:40, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="updateReminderWhenMinsBeforeStartIsnotCorrect_BEP144710020" duration-ms="133" started-at="2020-06-30T12:14:37Z" finished-at="2020-06-30T12:14:37Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at base.Testbase.executeSelectQuery(Testbase.java:209)
	at testData.TestDataCreation.createPOSTBodyForReminder(TestDataCreation.java:68)
	at Exposure.RestAssured.ReminderTests.updateReminderWhenMinsBeforeStartIsnotCorrect_BEP144710020(ReminderTests.java:567)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1188)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1113)
	at org.testng.TestNG.run(TestNG.java:1025)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
        </test-method> <!-- updateReminderWhenMinsBeforeStartIsnotCorrect_BEP144710020 -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="beforeTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:37Z" finished-at="2020-06-30T12:14:37Z">
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="afterTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:37Z" finished-at="2020-06-30T12:14:37Z">
        </test-method> <!-- afterTest -->
        <test-method status="FAIL" signature="updateReminderWhenIcorrectSchTrailID_BEP144710021()[pri:41, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="updateReminderWhenIcorrectSchTrailID_BEP144710021" duration-ms="142" started-at="2020-06-30T12:14:37Z" finished-at="2020-06-30T12:14:37Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at base.Testbase.executeSelectQuery(Testbase.java:209)
	at testData.TestDataCreation.createPOSTBodyForReminder(TestDataCreation.java:68)
	at Exposure.RestAssured.ReminderTests.updateReminderWhenIcorrectSchTrailID_BEP144710021(ReminderTests.java:579)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1188)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1113)
	at org.testng.TestNG.run(TestNG.java:1025)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
        </test-method> <!-- updateReminderWhenIcorrectSchTrailID_BEP144710021 -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="beforeTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:37Z" finished-at="2020-06-30T12:14:37Z">
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="afterTest" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:37Z" finished-at="2020-06-30T12:14:37Z">
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:Exposure.RestAssured.ReminderTests@37911f88]" name="afterSuite" is-config="true" duration-ms="0" started-at="2020-06-30T12:14:42Z" finished-at="2020-06-30T12:14:42Z">
        </test-method> <!-- afterSuite -->
      </class> <!-- Exposure.RestAssured.ReminderTests -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
